/* eslint-disable @typescript-eslint/no-unused-vars */
import esbuild from "esbuild";
import { sassPlugin } from 'esbuild-sass-plugin'
import process from "process";
import builtins from "builtin-modules";
import glsl from "esbuild-plugin-glsl";
import { esbuildPluginCssMerger } from './build/plugin-styles.mjs'
import { esbuildPluginManifestCopy } from './build/plugin-manifest.mjs'
import { esbuildPluginProjectExporter } from "./build/plugin-exporter.mjs";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin:
https://github.com/Falcion/UNITADE.md
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: [
        'source/main.ts'
    ],
    plugins: [
        sassPlugin(),
        glsl({ minify: true }),
        esbuildPluginCssMerger(),
        esbuildPluginManifestCopy(),
        esbuildPluginProjectExporter(),
    ],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "codemirror",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins],
    format: "cjs",
    target: "es2022",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "out/main.js",
    loader: {
        '.ttf': 'base64',
    }
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
