name: Bug report
description: Create a bug report to help to improve the project
title: "[BUG]: "
labels: ["bug", "priority/medium"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report, your contribution is invaluable in helping us improve the quality and reliability of repository.
    - type: markdown
      attributes:
          value: |
              Before you begin, please make sure you've checked if the bug has already been reported, if you find a similar issue, feel free to add any additional information or context that may help us resolve it more effectively.
              Also check FAQ on the wiki before asking some questions or reporting some bugs.
    - type: input
      id: contact
      attributes:
          label: Contact details
          description: If possible, write down the contact information if you need additional communication, if you want contact via "github", leave this field blank.
          placeholder: example@domain.com
      validations:
          required: false
    - type: textarea
      id: what-happened
      attributes:
          label: What the essence of the bug
          description: And tell the maintainers, what did you expect to happen.
          placeholder: Write that form, tell us what you see!
          value: ...
      validations:
          required: true
    - type: textarea
      id: obsidian-setup
      attributes:
          label: Obsidian setup information
          description: Please provide details about your setup (version, installed plugins, community plugins, etc.)
          placeholder: "... see comment the note below this input."
      validations:
          required: true
    - type: textarea
      id: obsidian-logs
      attributes:
          label: Obsidian logs
          description: If available, please paste relevant logs from application history
          placeholder: "... see comment the note below this input."
      validations:
          required: false
    - type: markdown
      attributes:
          value: |
              > [!Note]
              > You can do this by opening vault's settings and: "→ Options → General → Advanced → Notify if startup takes longer than expected → (timer icon)", with "copy to clipboard" to copy entire setup information.
              >
              > About collecting debug information:
              > https://help.obsidian.md/resources#Collect+debug+information
    - type: dropdown
      id: version
      attributes:
          label: Version of an project's essence
          description: What version of an project's essence are you running.
          options:
              - "3.2.5"
              - "3.2.4"
              - "Other (specify in issue)"
          default: 0
      validations:
          required: true
    - type: dropdown
      id: OS
      attributes:
          label: On what OS you have encountered the bug.
          multiple: true
          options:
              - Windows
              - macOS
              - Linux
              - Mobile (specify)
              - Not important
    - type: checkboxes
      id: terms
      attributes:
          label: Code of conduct
          description: By submitting this issue, you agree to follow our code of conduct — [reference is provided.](./../CODE_OF_CONDUCT.md).
          options:
              - label: I agree to follow this project's code of conduct
                required: true
    - type: checkboxes
      id: issue-policy
      attributes:
          label: Issue policy
          description: By submitting this issue, you agree to follow our issue policy — [reference is provided.](./../../docs/github/ISSUE_POLICY.md).
          options:
              - label: I agree to follow this project's issue policy
                required: true
