#!/usr/bin/env sh

    "$(dirname "$0")/_/husky.sh"

##commit_message=$(cat $1)

##commit_type=$(echo "$commit_message" | awk -F ":" '{print $1}')
##commit_types=$(cat versionrc.json | jq -r '.types[].type')

##if ! echo "$commit_types" | grep -wq "$commit_type"; then
##    echo "Error: Invalid commit type. Allowed commit types are: $commit_types"
##    exit 1
##fi

npx --no-installcommitlint--edit"$1"

exit 0